config/routes.rb
Rails.application.routes.draw do
  resources :manufacturers, only: [:new, :create, :index] do
    resources :cars, only: [:new, :create, :index, :show]
  end

  root 'manufacturers#index'

end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :manufacturer

  validates :year,
    presence: true, inclusion: { in: 1920..3000, message: "must be 1920 or later"}

  validates :name,
    presence: true

  validates :color,
    presence: true

  validates :mileage,
    presence: true
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  has_many :cars
  
  validates :name,
    presence: true, uniqueness: true

  validates :country,
    presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def new
    @manufacturer = Manufacturer.find(params[:manufacturer_id])
    @car = @manufacturer.cars.build
  end
  def create
    @manufacturer = Manufacturer.find(params[:manufacturer_id])
    @car = @manufacturer.cars.build(car_params)
    if @car.save
      flash[:notice] = 'Success!'
      redirect_to manufacturer_cars_path
    else
      render :new 
    end
  end

  def index
    @manufacturer = Manufacturer.find(params[:manufacturer_id])
    @cars = @manufacturer.cars
  end

  def show
    @car = Car.find(params[:id])
  end


  private
  def car_params
    params.require(:car).permit(:name, :color, :year, :mileage, :description)
  end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  def new
    @manufacturer = Manufacturer.new
  end

  def create
    @manufacturer = Manufacturer.new(manufacturer_params)
    if @manufacturer.save
      flash[:notice] = "Success!"
      redirect_to manufacturers_path
    else
      render :new
    end
  end

  def index
    @manufacturers = Manufacturer.all
  end


  private

  def manufacturer_params
    params.require(:manufacturer).permit(:name, :country)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/index.html.erb
<h1><%= @manufacturer.name %></h1>
<h5><%= @manufacturer.country %></h5>

<ul>
  <% @cars.each do |car| %>
    <li>
      <%= link_to("#{car.year} #{car.name} (#{car.color})", manufacturer_car_path(@manufacturer, car)) %>
    </li>
  <% end %>
</ul>

<div>
  <p><%= link_to("Record New Car", new_manufacturer_car_path(@manufacturer)) %></p>
</div>
<p><%= link_to("Home", root_path) %></p>

app/views/cars/new.html.erb
<h1>Record Newly Acquired <%= @manufacturer.name %></h1>

<%= form_for ([@manufacturer, @car]) do |f| %>

  <% if @car.errors.any? %>
    <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :name, "Model" %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>

  <div>
    <%= f.label :year %>
    <%= f.text_field :year %>
  </div>

  <div>
    <%= f.label :mileage %>
    <%= f.text_field :mileage %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.submit 'Submit' %>
  </div>

<% end %>

app/views/cars/show.html.erb
<h1><%= "#{@car.year} #{@car.name} (#{@car.color})" %></h1>

<ul>
  <li>Make: <%= @car.manufacturer.name %></li>
  <li>Model: <%= @car.name %></li>
  <li>Year: <%= @car.year %></li>
  <li>Color: <%= @car.color %></li>
  <li>Mileage: <%= @car.mileage %></li>
  <% if @car.description %>
    <li>Description: <%= @car.description %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CarListings</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<p><%= notice %></p>
<%= yield %>

</body>
</html>

app/views/manufacturers/index.html.erb
<h1>Car Manufacturers</h1>
<h3>Select a manufacturer to view or add cars</h3>

<ul>
  <% @manufacturers.each do |man| %>
    <li><%= link_to(man.name, manufacturer_cars_path(man)) %></li>
  <% end %>
</ul>

<%= link_to("Add a manufacturer", new_manufacturer_path) %>

app/views/manufacturers/new.html.erb
<%= form_for @manufacturer do |f| %>

  <% if @manufacturer.errors.any? %>
  <ul>
    <% @manufacturer.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
  <% end %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>
  <div>
    <%= f.submit 'Submit' %>
  </div>
<% end %>